### PR TITLE
Fix: elementary path sometimes are not computed due to this condition

### PR DESCRIPTION
**Pull request by Gonzalo-Mier**

### CODE REVIEW

**Comment by hbanzhaf** [comment]
Could you please check the paper: T. Fraichard and A. Scheuer, "From Reeds and Shepp's to Continuous-Curvature Paths," in IEEE Transactions on Robotics, 2004.

The additional threshold on delta should be explained there.

**Comment by Gonzalo-Mier** [comment]
Hi @hbanzhaf, sorry for the null description, I'll try it again:

The threshold is not explained there, but in "Continuous-Curvature Path Planning for Car-Like Vehicles" (https://ieeexplore.ieee.org/document/655130). In section 4.2 they said that an elementary path exists and is feasible if theta_lim is smaller than that threshold (and it gives a range for beta in that case). It doesn't say that elementary paths don't exist otherwise. This is the reason of the PR.

**Comment by hbanzhaf** [comment]
@Gonzalo-Mier: Can you give an example that shows that the current threshold is not needed?
@palmieri: What do you think?

**Comment by palmieri** [comment]
I would also propose if you can show this in a test file.

**Comment by Gonzalo-Mier** [comment]
Hi @hbanzhaf , did you have time to check this?

**Comment by hbanzhaf** [comment]
@Timple @vebjornjr: Could you have a look into the reported issue?

**Comment by Timple** [comment]
It looks like kind of a random number in the codebase. So I'm not against just removing it :slightly_smiling_face:

**Comment by hbanzhaf** [comment]
@Gonzalo-Mier Could you add to your test an assertion that the controls don't violate kappa_max nor sigma_max?

If that's the case, could you please visualise the denominator of the `sigma_0` equation, i.e., the values of `4 * PI * pow(this->D1(0.5 * delta), 2)` for `delta` in `[0, 2*pi[`. For `delta = 4.5948`, the denominator and thus `sigma_0` should become zero, which is not a valid value for the elementary path. 
@palmieri @Timple: FYI.

**Pull request closed without merging**
